### ISSUE TITLE
search filter loses focus after typing a few characters

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1002]
The lastest master branch code contains a bug whereby when a user enters text into the search filter on either the list view or the item view, after typing a few characters and pausing (>200ms) the search input loses focus.  This can be reproduced locally and on qa.languageforge.org
Users will experience this bug in a frustrating way as they will type a few characters and, depending upon their typing speed, the rest of the word(s) they are typing will be lost because the input focus is lost.  

![image](https://user-images.githubusercontent.com/3444521/125762477-3ba8cbbe-7349-40a1-ae4b-4737c2cba0cc.png)
In the above image, I typed "test" into the search box, but only "te" made it in before the input focus was lost.

Thankfully, languageforge.org does not have this bug, so this bug behavior was introduced in code that is yet unshipped.

I first observed this behavior when testing on QA, and have been able to repo locally on latest master.  @rmunn had a theory that the problem had to do with ui-router $state.go() and we were able to prove his theory correct and isolate the problem to the `$state.go()` line 272 in [editor.component.ts](https://github.com/sillsdev/web-languageforge/blob/6b5a12e0cd36148076784927d5aaf2a1eeffd820/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L272)

If we comment out the lines 
```
    this.$state.go('.', {
      sortBy: this.entryListModifiers.sortBy.label,
      filterText: this.entryListModifiers.filterText(),
      sortReverse: this.entryListModifiers.sortReverse,
      filterType: this.entryListModifiers.filterType,
      filterBy: this.entryListModifiers.filterByLabel()
    }, { notify: false });
```
then the problem of losing focus while typing is fixed.  Of course, the URL is no longer dynamically updating with the filter text, because that's what this code does.

**Comment by rmunn** [comment]
The version number of `angular-ui-router` in our `package.json` is 1.0.29, which is the current version. We used to have version 0.4.2, so I tried rolling the package back to 0.4.2 and the loss-of-input-focus issue went away. I'm currently narrowing down which angular-ui-router versions exhibit the behavior, and I'll comment again with the latest version number we can possibly use to avoid running into the unwanted behavior.

**Comment by rmunn** [comment]
The next `angular-ui-router` version after 0.4.2 series was 1.0.0 (and some 1.0.0 prereleases which I didn't bother testing), and 1.0.0 exhibits the loss-of-focus behavior we're trying to avoid. There's been one later patch release, 0.4.3, which does *not* exhibit the behavior. So the short-term solution to solve this issue is to just roll back our `angular-ui-router` version to 0.4.3 (we used to use 0.4.2) and call it a day. Once we've been able to push out a working deployment, we can revisit this and figure out why angular-ui-router exhibits this behavior, and how we can tell it "Don't reload components on the page when the state changes". (Because I think that's the root cause of this: it sees a state change and notifies AngularJS to reload the components on the page. We're setting `notify: false` in the options to `$state.go()` but something around that has changed between angular-ui-router 0.4.x and 1.0.0).
