### ISSUE TITLE
Thai writing system added to new (S/R) project

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#101]
From @rmlockwood

I have a Swedish FLEx project. I had a project created for it on
languagedepot today. I did the initial S/R to it and then I created a new LF
project and imported the Swedish project from languagedepot. When I went to
open the project I got this:

No vernacular words showing. When I examined a record I saw that for some
reason the Thai writing system was active for my words and not Swedish. I
don't recall ever having Thai as one of my writing systems for this project.
 
I won't touch the LF project so you guys can investigate.  
Thanks for looking into this strange behavior,

**Comment by rmunn** [comment]
A fix for this bug is under development at https://github.com/sillsdev/LfMerge/pull/40.

**Comment by rmunn** [comment]
GitHub auto-closed this issue because a bugfix has been checked in to the source code, but we don't actually want to close it until the bugfix has been deployed to the live servers, which hasn't happened yet. I'm re-opening the issue, and I'll close it once the bugfix has actually been deployed to users.

**Comment by rmunn** [comment]
This fix for this bug has been deployed to the live languageforge.org server, so we can close this issue now.
