### ISSUE TITLE
Go directly to project on sign-in

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1016]
Upon sign in, if there is only one project in the user's profile, go straight to that project.

Don't show the user the project selection screen for non-admin users.

- [x] If the user is part of multiple projects, go to the project that was last visited/used.
- [x] If the user has zero projects, take them to the projects screen with the "create project" button.
- [ ] Remove the breadcrumb link to "My Projects".  Don't need it anymore.
- [ ] If the user navigates (how?) to the /app/projects page, and they have at least project, redirect to that project.
- [ ] The project page should still function as an admin-only tool for listing projects

**Comment by alex-larkin** [comment]
Great ideas! How are users with multiple projects going to switch between them? I'm having a hard time visualizing it. Thanks.

**Comment by megahirt** [comment]
Great question, @alex-larkin .  Language Forge already has a compact project picker menu in the upper right hand corner.  Here's a screenshot.  Perhaps this picker would need to be promoted so users know about it.

![image](https://user-images.githubusercontent.com/3444521/127518444-8451b589-b8d3-4077-9679-924d07329c5b.png)

**Comment by alex-larkin** [comment]
Ah okay, looks good! I didn't remember that there were two "my projects" links- the breadcrumb one and this one.

**Comment by rmunn** [comment]
As I've read the code and looked into how to implement this, I've discovered that there are lots of places in the code that have a hardcoded redirect to `/app/projects` in various situations: after logging in, after signing up on the website, after clicking on a signup link in an invitation email, and so on. I think the simplest implementation of this feature is going to be a rewrite of the /app/projects Angular component so that instead of displaying a project list, it simply figures out which project to redirect to (based on the logic Chris outlined in the issue description), and then uses Angular's `$location` service to redirect to the appropriate project page.

Also, there's a rare case where it might be impossible to choose a project to redirect to, when the user belongs to multiple projects, but the most-recently-used project no longer exists on the website so we can't redirect to that one. In that rare case we'll still display the projects list as before, and once the user chooses a project that one will become their most-recently-used project, and they'll no longer see the projects list. (E.g., the user used to belong to three projects, and their most-recently-used project was project A. Project A's manager just deleted project A while the user was signed out. Now the user signs in, and since we can't choose which of projects B or C to redirect to, we present the projects list and let the user click on either B or C.)

**Comment by rmunn** [comment]
How did this get moved to the "Done" column? It's not done at all. Moving it back.

**Comment by rmunn** [comment]
Implemented, but I discovered that the original design (where the /app/projects view is not accessible at all) is less than ideal for Tech Support roles, because we often want to see the list of every project on the site so that we can join a new one. I also realized that the "List All Projects" link, which goes to /app/projects, will become a misnomer if we implement the original design. So I suggest the following design instead:

* Keep the behavior of redirecting to the most-recently-used project on signin, or on loading the site while signed in (loading the https://languageforge.org/ page while signed in redirects to /app/projects, which in turn will redirect to the most-recently-used project).
* Don't remove the breadcrumb, and don't remove the "List All Projects" entry in the menu
* Instead, the breadcrumb and menu entry will go to `/app/projects?redirect=no`, which will do exactly what you think it will

That way if someone is used to clicking on "My Projects" to select a different project they don't have to learn a new approach to navigating the site, but the behavior in the most common cases is still the useful one.

**Comment by megahirt** [comment]
This doesn't feel right to me.  Yes there are a number of places where /app/projects is hardcoded, but that should be a pretty simple find/replace.  Adding a ?redirect=no is just adding complexity IMO.

I accidentally left out a very important phrase in my original description: non-admin users should not go to the project page.  Admin users should still be able to access all projects via the project page.  /app/projects essentially gets promoted to an admin-only application.

Suggested implementation:
- [ ] add a new route: `/redirect/project` which performs the redirection logic
- [ ] only allow admins to access /app/projects
- [ ] change all applicable hard-coded `/app/projects` to `/redirect/project`
- [ ] comment out the breadcrumb - it adds no value.  We can add it back when there is a proper **project dashboard** to look at.
- [ ] remove All Projects link

**Comment by megahirt** [comment]
> Also, there's a rare case where it might be impossible to choose a project to redirect to, when the user belongs to multiple projects, but the most-recently-used project no longer exists on the website so we can't redirect to that one.

I don't think it's a big deal to just redirect to any existing project in that rare case.  Users know if they are on the wrong project and can switch immediately.

**Comment by rmunn** [comment]
I don't know how many users are like me, but I've gotten into the habit of clicking the "My Projects" breadcrumb when I want to go back and switch to a different project, rather than clicking on the dropdown menu. That's one reason why I didn't want to remove the breadcrumb: I feel that that would be a negative change for users who had gotten used to it. There's no reason, IMHO, to force people to use the menu if they *like* using the /app/projects list. And if they don't like using it, then the change to redirect-on-first-login will mean they pretty much never have to see it.

**Comment by rmunn** [comment]
Another note: the List All Projects link in the menu only shows if you have more than 10 projects, which means it's already close to an admin-only feature. The only non-admin users I can think of who might be a member of more than 10 projects are consultants, and for consultants, the /app/projects view *might* actually be useful, depending on their preferences.

**Comment by rmunn** [comment]
I should mention that I'm not wedded to the `redirect=no` query parameter; it just seemed like the simplest way to keep as much of the existing code as possible. Also, I don't think changing the URL to `/redirect/projects` would work, since the PHP code (as I understand it, I could be wrong) relies on the URL starting with `/app` to load the Angular HTML template. Perhaps `/app/projects-redirect` instead of `/redirect/projects`.

**Comment by longrunningprocess** [comment]
> How did this get moved to the "Done" column? It's not done at all. Moving it back.

:-D looks like you did it somehow
![image](https://user-images.githubusercontent.com/4412848/132526984-3f75605d-7b94-4827-b0b3-09599ad2c5da.png)

I'm glad you caught that though...

**Comment by longrunningprocess** [comment]
since this is turning into such a complex task after all, maybe this should go through a joint design discussion...it looks like too much conditional logic to me personally so I'd love to see some extraction/separation of logic that ensures authn, checks authz, then starts running business/convenience logic.  I wouldn't expect to see some stream of `if`'s that implements everything at once but something more like a service that handles its one thing well and doesn't clutter the basic intention of controller...additionally I see this logic in the component and it feels more like controller logic to me.

**Comment by megahirt** [comment]
Hi @rmunn 
> Also, I don't think changing the URL to /redirect/projects would work, since the PHP code (as I understand it, I could be wrong) relies on the URL starting with /app to load the Angular HTML template. Perhaps /app/projects-redirect instead of /redirect/projects.

I'm sorry I wasn't more clear in my implementation here.  `/redirect/project` is a PHP route, not an AngularJS route.  This would happen in a PHP controller.

**Comment by rmunn** [comment]
> since this is turning into such a complex task after all, maybe this should go through a joint design discussion...it looks like too much conditional logic to me personally so I'd love to see some extraction/separation of logic that ensures authn, checks authz, then starts running business/convenience logic.

I agree that a design discussion would be good, so I'll hold off on this one for a day until we can discuss it at our standup meeting. I'll just mention that since we're going to be replacing the PHP server with something else at some point, hopefully soon, I'm strongly inclined not to spend time on refactoring the PHP server in any major way right now. IMHO that would just be wasted effort that delays us getting to the point where the project is actually maintainable going forward.

**Comment by rmunn** [comment]
Summary of our design meeting:

* We will not remove the breadcrumbs or the "List All Projects" entry in the menu
* The existing `/app/projects` page will remain unchanged
* We will implement a new PHP route `/redirect/projects` that chooses a project to redirect to
    * If `/redirect/projects` cannot find a valid project to redirect to (e.g., the most recently used project was deleted), it will fall back to `/app/projects` as a last resort
    * Whichever project the user chooses from `/app/projects` will become the new most-recent project, and next time `/redirect/projects` will have a valid project to go to
* All server-side code that redirects users to `/app/projects` (after logging in, after signing up via OAuth, etc.) will instead redirect them to `/redirect/projects`, which will in turn redirect them to their most recently used project

This means that the client-side code will be pretty much unchanged, and all the changes will be server-side. So I'll back off the client-side changes I made in #1140 and implement those changes server-side instead.

**Comment by megahirt** [comment]
Just a small nit: the new route should be singular: `/redirect/project`

I will also go ahead and update the issue description task list to reflect our design decisions.
