### ISSUE TITLE
PgUp / PgDn for keyboard entry navigation

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1017]
Add ability to use the Page Up and Page Down keys to navigate previous / next through the list of entries.

Page Up = previous entry
Page Down = next entry

**Comment by rmunn** [comment]
Might be confusing to some users who are used to scrolling their browser window with the PgUp and PgDn keys. In which case it might need to be configurable on a per-user basis.

Though making it configurable would be rather tricky, as so far we don't have any such thing as a "configure my site settings", not even a light/dark theme, so we'd end up having to implement a "My settings" tab in the user profile, and make the HTML only configure the keyboard shortcuts once the personal settings are loaded... I'm talking myself out of the idea.

I'll leave this comment anyway, though, because it's something to think about: will users who prefer PgUp and PgDn for browser scrolling be annoyed by this change?

**Comment by megahirt** [comment]
I want to move the editor away from web page scrolling as much as possible
and only scroll those elements which have content off screen (list of
entries, and entry editor surface).  The page itself should not scroll,
ideally.  So I wonder what the browser would do with a page up / page down
when the focus is on the page as a whole?  This seems like undefined
behavior because the user should know what they are paginating.  If you
think users are familiar with keyboard scrolling of the page, what key
combination would you suggest instead?

**Comment by alex-larkin** [comment]
Since standup I have given more thought to this. 

Would it be possible to use the left and right arrow keys for entry pagination instead? I think that would be more intuitive, since the GUI buttons show left and right arrows. 

Regarding the page up and down keys, I think that it would be good if they did bring the content up and down, regardless of where the focus is. 

From an average user's perspective, they don't know about focus or objects/containers. They just know that their data is lower down, and I think that they generally expect the page down key to get them there. 

The only distinction i would make is this: if in entry view the world list is visible on the left, check if the mouse is over the list. If so, make page down lower the list. Otherwise, lower the entry content. 

Sorry I didn't think of this sooner. Hopefully arrow keys aren't too different from a programming perspective. 

Thoughts? 

Later I also want to link to the issue on hiding the top entry paragraph, to develop the conversation a bit more. As soon as I get the chance 😃.

**Comment by alex-larkin** [comment]
But of course if the cursor is active the left and right arrow keys should have their normal function.

**Comment by megahirt** [comment]
> From an average user's perspective, they don't know about focus or objects/containers. They just know that their data is lower down, and I think that they generally expect the page down key to get them there.

@alex-larkin my observation of users using Language Forge is that their first inclination for scrolling is either a touch screen or a mouse wheel scroll.  I have yet to see anyone use <kbd>PgUp</kbd> or <kbd>PgDn</kbd> to scroll the appropriate div/container.  I picked <kbd>PgUp</kbd> and <kbd>PgDn</kbd> because I felt like they are rarely used but also seem appropriate to take on a "paging" function through the entries.  I feel like this is the better solution over arrow keys.

In my experience, <kbd>&#8592; Left</kbd> and <kbd>Right &#8594;</kbd> arrow keys having different functions depending upon input focus would cause serious user confusion.  Users may not necessarily understand "focus" and therefore not be able to explain why it works sometimes and not other times.

**Comment by alex-larkin** [comment]
> ...users may not necessarily understand "focus" and therefore not be able to explain why arrow keys work sometimes and not other times...

In this case, page up and page down would take users to a new entry, regardless of focus?

**Comment by megahirt** [comment]
@alex-larkin yes that is the intention
