### ISSUE TITLE
Enter key should move to next field

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1018]
Currently, pressing enter inside a mult-text field does nothing.  The new behavior should move the cursor to the next field.  Should it also save the entry?  This could be problematic with losing input focus.

- [ ] capture Enter key press and move to next field

**Comment by rmunn** [comment]
One time when it should certainly *not* save the entry is if the field was empty, i.e. the user was just pressing Enter on an empty field because they want to get to a field further down that they *actually* want to edit. Even leaving aside issues with losing input focus, that would be a server round-trip for what turns out to be a no-op.

**Comment by alex-larkin** [comment]
Good ideas. I would suggest that Enter _not_ go to the next field for multiple-line data fields. I think hitting some key combo like Shift+Enter or Ctrl+Enter will be unknown or difficult for most users.

**Comment by megahirt** [comment]
@alex-larkin this is a good point and I think we need more research to determine what users expectation is.  My thinking in initial observation is that people wanted to press enter to move to the next field instead of a mouse click.  In general, most data fields are displayed as wrapping single line data in FLEx and I would want to do the same in LF.  Can you point me to instances where encoding new lines in the dictionary data would be a good thing?  I would think this would cause problems for publishing in a big way...if you allow users the ability to add newlines you lose control of the formatting of the entry in a lot of ways.

**Comment by alex-larkin** [comment]
Good observations Chris. We'll have to think about this carefully! One category where we will certainly want to be able to make new lines are the notes fields. I'm on my phone right now and can't remember what FLEx behavior is, but when I imported from Toolbox I often had to consolidate many '/n' notes fields into a single big note. 

I'll take a look at FLEx later today to see if such notes are displaying as I recall, and if there are any other fields where we would want multiple lines.

On mobile I can certainly see how the Enter key, morphed into the 'next field' key, would be handy. But all the same what I have seen with the Quechua is that they generally prefer to interact directly with the GUI than use any kind of key shortcut (even if the shortcut is a single key 😳). All the same, maybe a good compromise would be for Enter to advance to the next field, unless the active field is a notes field. 

For computers, would it be hard to set up the arrow keys so that they can also go between data fields? Possibility the up and down keys.

**Comment by alex-larkin** [comment]
Here's an example of a General Notes field with two unrelated notes. 

![image](https://user-images.githubusercontent.com/82162128/127558246-44499d5e-1391-4a74-b172-65fb47d1f524.png)

In my database I have almost 1200 General Notes. There are also many other notes fields in different subcategories. Unfortunately I can't add another General Note object.

**Comment by megahirt** [comment]
This is good discussion, however I think my initial idea to make the "return" key go to the next field has significant enough issues that I will close this.  It wasn't requested by an user, so we have better things to work on right now
