### ISSUE TITLE
entry "unreadness"

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1025]
Just an idea:

Keep track of entries that have been seen by the user.  Distinguish unread entries in the list somehow.

**Comment by rmunn** [comment]
That information would need to be tracked in each project's database; I think it was a mistake to put the `activity` collection in the `scriptureforge` database, but it's probably too late now. We'd need a `viewedEntries` collection that is keyed by entry ID and has a `readBy` field (which would be an array of user IDs). We'd use the [`$addToSet` operator](https://docs.mongodb.com/manual/reference/operator/update/addToSet/#mongodb-update-up.-addToSet) to add the user's ID to the array if and only if it doesn't exist in the array already, which would be perfect for this feature. It even creates the array field if it doesn't already exist.

**Comment by rmunn** [comment]
Then when building the list view, we'd do a Mongo query on `viewedEntries` that looks like `{ readBy: userId }`. When you do `find({ arrayField: 'singleValue' })` in Mongo, that means "find all documents where arrayField *contains* 'singleValue' ". Then the projection part of the find could just return the entry ID. The UI would have a simple Javascript Set of read items, populated from the results of the Mongo query, and it would apply an `unread` class if `! readSet.has(entryId)`.

**Comment by alex-larkin** [comment]
This sounds like a nice feature! If implemented, I think it would be good to be able to bulk-edit the "viewed status". For example, a user could mark all 7000 entries as viewed upon import, and then only see the new unread entries as other users create or edit them. Or, mark an individual entry as "viewed" or "unviewed".

Also, I think it would be very useful to be able to search for entries that I have interacted with and that have since been interacted with my other users. Not sure where the best place to put that in Github would be.

**Comment by megahirt** [comment]
@alex-larkin You can describe the desired behavior of your idea in a card, and then place it in the ideas column on the features board that Billy created.

**Comment by alex-larkin** [comment]
Will do! 

Distinguishing unread entries: They could have a slightly different background color (like notes in Paratext).

**Comment by alex-larkin** [comment]
Here's an example from Paratext: unread notes have a yellow background. 

![image](https://user-images.githubusercontent.com/82162128/127559905-38bd4d1d-0c79-41e5-8161-1611cb72b420.png)

**Comment by rmunn** [comment]
The idea I listed in https://github.com/sillsdev/web-languageforge/issues/1013#issuecomment-894067166 (a "Needs work"/"Completed" status for entries along with a counter to track how many are done so far) also relates to this "unreadness" idea, at least a little. Because if we use a background color to mark unread entries in the list view, perhaps we could also include some kind of background color or highlight to mark entries with the "Needs work" status in the list view as well.

**Comment by alex-larkin** [comment]
@rmunn, I think that if we just use the color tagging suggested in #1008, it would accomplish the same thing. You can see my comment in #1013 too. Thanks!
