### ISSUE TITLE
performance testing: what are the costs of having all entries loaded at all times?

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1127]
The LF Editor downloads all entries to IndexDB but for performance reasons does not load all entries into the UI / page.  It loads a section of 50 at a time in an "infinite scroll" feature that causes the vertical scroll bar to jump as it goes down the list.  With this implementation, the scroll bar does not hold meaning and cannot indicate one's position in the dictionary.  It is simply used to load more entries.

I'd like to understand the performance impact on various devices if change the editor to "load all entries".  Where is the sweet spot of loaded entries that gives good performance and still loads most of the dictionary?

Is it feasible to load 10K entries into the UI?  How long does this take on mobile?  Is the application noticeably slower, both after load time and time it takes to load the editor?  This performance testing will inform UI changes we may be able to make to improve the user experience.

**Comment by rmunn** [comment]
If the scroll bar position should be meaningful, one trick we could use is to have the entries array populated with mostly `undefined`, with 50 entries (initially) actually containing real data. The UI would be configured to show an `undefined` array result as "Loading..." or just a spinning wheel icon. When the user moves the scrollbar such that a section of the array containing `undefined` entries comes into view, that chunk would be loaded from the database with a server RPC call. (And, if memory space is an issue on mobile devices, another chunk of the array, which has now scrolled off the screen, could be "paged out" by setting the content of that chunk back to `undefined` until it's needed again.)

This trick would make implementing filters a little difficult, because the filter would need to be run on the server side to obtain a count. From the client's perspective, it would need to be able to say "Give me items 51 through 100 of the 'Contains comments' filter results".
