### ISSUE TITLE
Allomorphs

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#114]
Right now in LF allomorphs are not displayed. Allomorphs, which are phonologically conditioned alternate forms, are very important in tracking all the valid forms of a morpheme. I realize that it is probably a lot of work to have the capability of adding and removing allomorphs along with their environment constraints, but would it be possible to show a read-only display of the allomorphs and maybe even the environment string(s)? It would be so helpful to know that the forms exist in the database even if a person has to go to FLEx to work with them.

Thanks,
Ron

**Comment by megahirt** [comment]
Thanks @rmlockwood for this suggestion.  As you've noticed, we are completely ignoring this data in LF because of the complexities of implementing it when faced with other more basic features (solid searching / sorting, for example).  I'll talk this over with the team to decide if this is something we can do for cheap.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-28
