### ISSUE TITLE
bug: Some LF updates not being reflected in PWA installs

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1233]
**Describe the bug**

As described in the last few comments of #1228, an update to the CSS of Language Forge was not carried through to my PWA install of LF on Android. We need to determine the issue and make a fix so that PWA users are getting all of the LF updates. 

**To Reproduce**
1. Install LF as a PWA on a device 
2. Make a CSS change to the UI in Language Forge and release it to production
3. Open the LF on the device and notice that the change is not reflected
4. Uninstall the PWA and reinstall it. Notice that the UI change is now visible. 

**Expected behavior**
All LF updates to be immediately visible on PWA installs, without needing to reinstall the app. 

**Screenshots**
No screen recording obtained of the workaround, but see #1228 for other relevant screen recordings. 

**Desktop (please complete the following information):**
It is unknown if this particular bug also affects desktop PWA installs, as #1228 only changed the UI on mobile. More investigation needs to be done. 

**Mobile (please complete the following information):**
 - Device: Samsung Galaxy s10e 
 - OS: Android 10.0
 - Browser: Chrome

**Android App in Google Play**
For Mobile, are you using the Language Forge Android app in the Google Play store?  [Yes/No]
No- PWA

**Additional context**
None

**Comment by megahirt** [comment]
https://medium.com/google-developer-experts/workbox-4-implementing-refresh-to-update-version-flow-using-the-workbox-window-module-41284967e79c

Haven't read the article yet but google search looked good

**Comment by longrunningprocess** [comment]
> https://medium.com/google-developer-experts/workbox-4-implementing-refresh-to-update-version-flow-using-the-workbox-window-module-41284967e79c
> 
> Haven't read the article yet but google search looked good

I see `"workbox-webpack-plugin": "^3.3.1",` in our deps so I need to follow that dep a little but the article is referencing wb4.

**Comment by longrunningprocess** [comment]
I'm still researching but I didn't find that a filename that workbox is generating is not the file it's looking for at runtime so I need to try and figure out where that disconnect is in the build process.

**Comment by megahirt** [comment]
@longrunningprocess As far as I know, our workbox usage is limited to creating an empty service worker that does mostly nothing (I think it provides a single offline page, which I find largely useless).  Why not rip out the workbox v3 and replace it with wb v4 to solve this issue?  Any trivial code can be re-implemented in wb 4.

**Comment by longrunningprocess** [comment]
yeah, we're sort of thinking the same.  I did install the latest just see where that would get us.  It's actually up to 6 these days and when I did that, it added a bunch of font-awesome stuff in the precache so I was going to need to look through that a bit and see why it was doing that.  Additionally, there is a recipe already to achieve the "offline" file approach you all implemented initially, https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offline_page_only,  so I was going to look at reimplementing that since it was isolated to `app` and `auth` urls only...I didn't know why necessarily but I didn't really have access to anyone involved to discuss at the time so it's just being delayed.

Here's a "standard" approach which is much simpler than the extra stuff that was done for LF:  https://github.com/silinternational/wecarry-ui/blob/develop/rollup.config.js#L70.  It basically says, look for these file types in this directory and here's where I want you to drop the file you create.  As soon as we start deviating from the typical pattern, it's begins to get more complicated.

My plan today is to simply drop in a standard, simple approach with the latest workbox and see if/why that won't work for LF.
