### ISSUE TITLE
GHA unit test reporter

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1269]
**Is your feature request related to a problem? Please describe.**
There is an action available that will produce really pretty test results in our PR's and @megahirt would like to see us integrate it.

**Describe the solution you'd like**
refer to discussion here for details of previous attempt:  https://github.com/sillsdev/web-languageforge/pull/1258#discussion_r760716331

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by megahirt** [comment]
Without this reporter, the PR only contains a pass/fail for the unit tests, and you don't have any information on how many tests pass or fail.  To find out which tests failed, you have to go into the GA logs to that specific section in order to find out.  This reporter parses the test output and displays it as a comment in the PR.
