### ISSUE TITLE
user support / research: investigate sorting of entries with diacritics

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1282]
See https://community.software.sil.org/t/sort-alphabetically/5667/6 for details.

**Comment by longrunningprocess** [comment]
@alex-larkin or @megahirt , do you all think there could be any overlap to #1266 (feat: Improve diacritic-agnostic search result ordering)?  For example, if we implement #1266, would Ken's problem go away or is sorting a very independent matter to the ordering in #1266?

**Comment by megahirt** [comment]
My current understanding of these two issues is that they are quite different, and #1266 could be rephrased as search result ranking rather than sorting.  Whereas this issue is about sort order based upon the first character of the head word.  Sorting is actually a complex beast that language forge for better for worse doesn't handle all of the complexities, it simply sorts based upon the first character.

**Comment by alex-larkin** [comment]
I agree with @megahirt's assesment. 

FLEx, for example, has a lot of programming to be able to handle all of the ins-and-outs of sorting. For example, some two-letter combinations like "ph" "sh" and "ch" are actually -linguistically speaking- a single sound. They just happen to be represented with two characters- a "digraph." Some languages (Including Spanish, until recently) sorted all words treating digraphs as a single character. So, for example, you would see "laguna," then "luz", and then "llama", since "ll" is a digraph, and comes after "l". 

I'm at a loss as to why Ken experienced that ordering. Copying the characters from his project (most notably the last two entries from his printscreen), I see that the u is 0075 and the q is 0071 with 0307 added on. I wonder if there is some sort of special sorting rules for characters with diacritics. 
![image](https://user-images.githubusercontent.com/82162128/150265162-21b7a6e2-d476-44aa-8143-ebf6536619c9.png)

Understanding LF as a lexicon development tool leads me away from wanting to recreate FLEX's sorting abilities. That would be a lot of coding and added complexity. Users can build their lexicon in LF using default sorting, and then set their ordering preference upon export- be it to a DAB app or PDF (via FLEx). (Webonary, last I heard, just sorts by Unicode too). 

Then again, sorting still has to make sense! And I don't understand why the u is coming before the q for Ken. 

As a side note, I couldn't reproduce the order of entries in the printscreen Ken shared. There is also a big difference in total number of entries, so I wonder if we are looking at the same project. 

Any thoughts on why that u came before q?

**Comment by megahirt** [comment]
I suspect that sorting is happening with NFC data, so whatever code point
the "q + diacritic" is, it comes after plain "u"

**Comment by longrunningprocess** [comment]
That helps, I'll start setting up some data locally to reproduce this and see where the relevant code is in preparation for a fix.

**Comment by megahirt** [comment]
I've just taken a look at the sort code and there are some places where I'm scratching my head asking "why are these methods conflated?", but anyway.

The core sort logic is contained in [getSortableValue()](https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/core/offline/editor-data.service.ts#L330)  The method [sortList()](https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/core/offline/editor-data.service.ts#L673) is a helper method that is run on the multiple "lists" that the application maintains locally: `entries`, `filteredEntries`, `visibleEntries`.  sortList() has a bunch of logic related to "ranking" the filteredList, which I believe is where work needs to be done to address #1266 , but at the end of the method it calls [sortListAlphabetically()](https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/core/offline/editor-data.service.ts#L717) which is what this issue is concerned with.

In summary sortListAlphabetically() invokes getSortableValue() for each entry.  What this method returns is highly dependent on the data in the entry, and I'm thinking we need to take a close look at the data in Ken's dictionary to understand what is going on.  It is also user-customizable based upon the "sort by" drop down in the UI.

![image](https://user-images.githubusercontent.com/3444521/150469179-a454651f-27b3-4f0f-943d-0e3ea920cc09.png)

You will notice that the sort function above takes some liberties on how it sorts, specifically it picks a three letter code (hopefully a relevant one!) to send to the JS International Collator, so that it can do script-specific sorting.  As you might guess, this is the point at which we defer sorting complexity to the Unicode collator which comes with the user's OS.  Those working in minority language dictionaries where their sort order differs from the one defined by the majority language script are not going to be happy.  FLEx has a lot of sort logic under the hood to handle this situation and allow for customization, including implementing a custom sort rules syntax, but for LF we don't prioritize this since it is a lot of work to implement.

![image](https://user-images.githubusercontent.com/3444521/150468941-79915e2e-e527-4af2-9cc8-03f83bfc4bb9.png)

At the moment I cannot recall how the dropdown values are populated.  But that's not really in scope for this issue.

**Comment by longrunningprocess** [comment]
![image](https://c.tenor.com/4BPYtmrJb44AAAAC/pororo-dizzy.gif)

Thanks @megahirt , I'm going to need to pair on this one...

**Comment by longrunningprocess** [comment]
ok, so with the learning I've been doing over in https://svelte.dev/repl/949c36218f254d3cb2017fea1b297995?version=3.46.2, I can better undestand @megahirt 's findings above.  As I understand it, we need to look at the data since it seems we're doing things right programmatically.

**Comment by megahirt** [comment]
There isn't anything actionable on this issue so I am closing.
