### ISSUE TITLE
LD not showing updates from LF

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1360]
From Sargon: 

Last, I have reported that [Send/Receive] (sync) button feature was inactive. Now it’s but when I click on it to update the repository, then I go to FLEx and click on Send/Receive button, I don’t see my changes from LF sync’ed up in FLEx. When I go to LF repository, I see my last activity was from 2/3/2022. That tells me that today’s changes in LF were not uploaded to the repository. Can you please look into this?

![ld](https://user-images.githubusercontent.com/3444521/160414685-0bf53f82-bfe0-4de5-ab9e-8263b604a6ac.png)

Regards,
Sargon

Project name: Du****** Flex

**Comment by rmunn** [comment]
Finally tracked this down. The cause of this one was the .fwdata file getting truncated somehow, perhaps due to a full disk; the .bak file was 6.5 megabytes but the .fwdata file was only 300 kilobytes, and terminated right in the middle of an XML element. The result was an error in the log: "LCM: Unknown error: File is not a valid FieldWorks project file." We don't have any code that catches that error, because I'd never encountered a truncated .fwdata file in all my testing, so LfMerge didn't report any problems to the user.

I've now restored the .fwdata file (by re-cloning the project from Language Depot) and did another Send/Receive, and that seems to have worked normally. The project should be unblocked now.
