### ISSUE TITLE
bug: Can not create a non-S/R project on mobile due to element overlap

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1411]
**Describe the bug**
When creating a new non-send/receive project on mobile, the footer warning blocks the GUI, preventing the user from moving forward. 

**To Reproduce**
1. Go to "My Projects"
2. Tap on 'Start or join a new project'
3. Tap on "Create a non-send/receive project (not recommended)"
4. See warning footer blocking the Next button

**Expected behavior**
Be able to see and tap the Next and !Back buttons

**Screenshot**
[Screenshot_20220525-184106_Chrome.jpg](https://user-images.githubusercontent.com/82162128/170388172-495ef776-59cc-4796-87e0-45657a6529ec.jpg)

**Mobile (please complete the following information):**
 - Device: [Samsung Galaxy S10e]
 - OS: [Android 10]
 - Browser [chrome]

**Android App in Google Play**
For Mobile, are you using the Language Forge Android app in the Google Play store?  [No]

**Additional context**
* Using browser, not PWA
* Could this issue also manifest on other pages or contexts where error or warning messages are displayed on mobile device?

**Possible Solutions**
* Add white space at the bottom of the page
* Change display properties so that the warning shows higher up on the page, as with tablet and desktop
* Change other parameters so that there is no overlap.

**Comment by rmunn** [comment]
Another possible solution is to provide a close button (an X) on the warning message so that it can be dismissed. This would fix the issue on all pages, and would probably be the simplest solution.

One way we could catch this, and similar, issues in the future is to expand our E2E tests to run on mobile-sized screens as well as desktop-sized screens. An E2E test that involved clicking through the "Create a non-SR project" screen would have caught this, because when it tried to click on the Next button Playwright would have thrown an error saying "Tried to click on the Next button but a different element intercepted the click". Playwright is smart enough to scroll the screen if necessary to find the element it's trying to click on, but if that element is completely overlayed by another element then the E2E test will fail, as it should.

So there are two action items here:

1) Add a Close button (an X in the corner) to our warning messages to dismiss them.
2) Expand the E2E tests to include mobile-sized screens.

**Comment by alex-larkin** [comment]
These are great ideas and great action items!
