### ISSUE TITLE
bug: 500 server error on activity dashboard when accessing Tampuan Flex project

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1536]
**Describe the bug**
In some cases (I'm still trying to figure out exactly in which cases), switching between projects via the "My Projects" dropdown or via the Projects listing, results in a 500 error with a message similar to "don't have privileges accessing api method"

**To Reproduce**
Steps to reproduce the behavior: Add yourself to the Tampuan Flex project and click the link.
Alternatively visit https://languageforge.org/projects/tpu-flex if you are already a member.

https://languageforge.org/app/lexicon/5a2f5fa88b2147063928aaf3 is the lexicon application link which still works.

**Comment by longrunningprocess** [comment]
# Use cases currently failing

## new entry gets added to two different projects simultaneously

## `500` after deleting a project

## no work-around for Tampuan Flex project

**Comment by longrunningprocess** [comment]
the issue is with the `checkPermissions` call and its assumption that the `projectId` is set... we may consider either finding a different UI treatment that would allow a user to get to the dashboard or we will need to create some awareness of an incoming project code within the legacy authz model, i.e., checkPermissions and/or Sf.php.
