### ISSUE TITLE
feat: Better UI for adding entries

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1538]
**Is your feature request related to a problem? Please describe.**
There is no explanation of how to add an entry. The current method (plus sign in the ~ top left area) is not hoverable.

**Describe the solution you'd like**
Make it look more like a button. Make the button hoverable (change color; tell you what it does).

**Describe alternatives you've considered**
Put this button in another place (probably unnecessary).

**Comment by megahirt** [comment]
@longrunningprocess I am interested in your design thoughts on this.

**Comment by longrunningprocess** [comment]
My first inclinations:

1. remove the '+' from the "Showing all..." title bar
2. remove the shish kabob from the Entry header
3. center the entry navigation on the editor header
4. put a shish kabob menu all the way to the right on the editor header where the dropdown will reveal items for "show extra fields, comments, activity, delete"  

![image](https://user-images.githubusercontent.com/4412848/198701646-16b2f846-2f66-46b5-b067-7cb1ef55b2bf.png)

The next decision would be whether to make an Add button prominent or stick it under the menu as well... if it's a very common function for the user, then I'd suggest making it prominent otherwise I'd put it under the menu.
