### ISSUE TITLE
Arabic Script lexemes not displaying correctly (cut off)

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#154]
See the below image that shows lexemes being cut off in the word list.
![image](https://user-images.githubusercontent.com/7088137/29973692-b61318ca-8f30-11e7-903e-f2a40a612a1d.png)
For comparison see the shape of these Arabic script words in the Entry Edit view.

**Comment by megahirt** [comment]
I think this is related to a less than 1 line height.  I'm wondering if
there's a way to have a smaller line height without text cutting off?  Or
maybe we have to have the meaning and word be relatively positioned instead
of using line height to make them fit closer together.

**Comment by megahirt** [comment]
Could also try "overflow: visible" on the span or div to see if that fixes
it

**Comment by megahirt** [comment]
Hi Ron,

On my machine I believe I'm seeing the Arabic script correctly, and I think it's because of the font (or lack of font) installed on my machine.  Can you perhaps tell me what font you think is being displayed and a link to download it so I can see the "cut off" on my development machine?  The font you have showed me is different than what I have on my machine.  Thanks for your help.

This is what I'm seeing:
![image](https://user-images.githubusercontent.com/3444521/30010919-b4285b4a-915d-11e7-9d84-1e08ea42dad8.png)

**Comment by megahirt** [comment]
Hi @rmlockwood I have pushed a hotfix that changes the CSS overflow property in hopes that this will resolve the immediate issue.  I am currently thinking about alternate ways to layout the compact list item display, including making the headword and meaning display on the same line and just wrap.  I'll try and mock something up so you can give me your feedback.

In the meantime, can you see if the fix I just pushed out fixes the clipping you are seeing?

**Comment by rmlockwood** [comment]
The words are no longer clipped. Thanks.

**Comment by megahirt** [comment]
OK, glad this is resolved.

**Comment by rmunn** [comment]
Glad this is fixed. But I think that the solution, removing the `overflow: hidden` line from the CSS, will possibly cause some ugliness in left-to-right languages: that view was originally designed with left-to-right languages in mind, where the word would appear on one line and its meaning on the next line. We used to have some issues where a long lexeme in an LTR language would wrap onto two lines, and "sit on top" of the definition / gloss, looking ugly. Which was the original reason for setting `overflow: hidden` in CSS.

Now, as I look at the screenshots above, I'm wondering if we should have two different view templates:

1. Word and meaning are both LTR or both RTL: same as before, word on one line and meaning on next line, and `white-space: nowrap` is used to [make sure that the word won't wrap to the next line](https://stackoverflow.com/a/7546415/2314532). Then `overflow: hidden` would also ensure that long words won't "stick out" past the right-hand side of the line.
2. Word is RTL and meaning is LTR, or vice-versa (word is LTR and meaning is RTL): a one-line view, with two elements in the line: the LTR part on the left and the RTL part on the right. I.e., in this example, the word would be on the right and the meaning on the left. That way there's room to display both the word and its meaning, and neither one can flow into the other since they're two separate "blocks" in the page layout. In this view, since both the LTR and RTL sides have less horizontal space to work with, we do *not* set `white-space: nowrap`, and we allow long words to overflow and make the box higher (e.g., we use `min-height` instead of `height`). This matches how FieldWorks renders its text list: long lexemes wrap to multiple lines.

**Comment by rmlockwood** [comment]
In my opinion, either option would be fine.

Ron
