### ISSUE TITLE
Display problem if only have 'citation form' and no 'word' entry

### ISSUE THREAD

**Issue by wilkwalk94** [sillsdev/web-languageforge#157]
Hi, as the 2 images below show, there are problems with words that only have a citation form and no 'word' (lexeme form). Once you click on an entry it recognises the citation form, but until you do that it only shows the national language gloss which is frustrating. 

I'm not even sure what sort order the words are in. I have a large number of entries with only citation form. Those that have a word form entry do correctly show up by citation form which is good, but i had to scroll down a long way to find those!

![image](https://user-images.githubusercontent.com/31653061/30056863-f6e7f24e-9223-11e7-824f-990ef9cd59fe.png)

![image](https://user-images.githubusercontent.com/31653061/30056897-18eff4fe-9224-11e7-9146-08e3ee5d0756.png)

P.s. I'm surprised you have to sign up to github to be able to send a bug report, i wonder how many people will do that, I would have thought most people would expect an email address that they could send a report to.

**Comment by megahirt** [comment]
Hi David,

Thank you for this bug report and I'll look into this soon, at the latest
when I'm back in the office on Thursday.  I just set up JIRA for user
support so we will have e-mail based issue tracking soon.  You can try it
out now by emailing issues@languageforge.org

Blessings,

Chris

**Comment by megahirt** [comment]
Hi David,

Thanks again for this bug report.  Frankly we haven't done a lot of testing
with data sets that don't have lexeme forms, but I think in practice this
is quite common.  The sort order is messed up because it's not taking into
account the citation form when sorting, only on display.  This is the first
bug.  The second is a timing issue in the display mechanism where the value
for display is calculated too early, before the required info is needed to
decide between citation form and lexeme form.  I'll work on a fix for this
and post here again when there's an update.

Thanks,

Chris

**Comment by megahirt** [comment]
I have a commit 3820368cf8f48b11e5958c1a55d24cdf21d4d0ff to address this bug.  Will close this issue when the fix has shipped.

**Comment by wilkwalk94** [comment]
Thanks for those explanations, just to comment yes I think it probably is quite common to only have citation forms. In our case the data is based on a Rapid Word Collection workshop where everything is entered in the citation field by the participants, only later will I generate the root form from that and put it in the lexeme field (word form).

**Comment by megahirt** [comment]
Thanks again for the bug report.  This fix has now been shipped to languageforge.org  In some cases I recommend doing a Ctrl-F5 in case the changes are not immediately reflected in your browser.
