### ISSUE TITLE
Arabic script not showing in the SBF project side dictionary index for contributor

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#159]
In the side panel only the English gloss shows and not the Arabic script headword. I'm logged in as contributor for the project abbreviated SBF.

**Comment by rmunn** [comment]
I believe this may be related to the Citation Form feature. We recently fixed the side index so that it shows the citation form if there is one, and it shows the contents of the "Word" field if there is no citation form. But on the SBF project where the Citation Form field is turned off for contributors, our code is doing the wrong thing: it can see that there is a citation form, so it tries to use that form instead of the "Word" field. But because the citation form is hidden from the user, its contents can't be displayed, so the result is that nothing at all is shown for the Arabic-language part of the side index.

There are two possible ways that this case could be handled:

1. If the Citation Form field is hidden from a particular user, they do not see the citation form in the side index, but they see the lexeme form (the contents of the "Word" field) instead. ADVANTAGE: The user sees the same word form on the left and on the right, and can modify it. DISADVANTAGE: The word form that contributors see in the side index is different from the word form that the project manager sees, which might hinder communication between project members.

1. If the Citation Form field is hidden from a particular user, they see the citation form in the side index, even though the Citation Form field is hidden from them and they cannot modify it. DISADVANTAGE: The user does *not* see the same word form on the left and on the right, and may be confused about why the Word field on the right doesn't match the word form that he's seeing on the left. ADVANTAGE: Everyone in the project sees the same word form in the side index, so if one project member says "Word X has the wrong part of speech" and uses the citation form for word X, the other project members will be able to find that word in the side index without confusion.

We'll need to decide which of these two approaches is likely to serve our users' needs best.

**Comment by megahirt** [comment]
Or maybe a third option is that the citation form / lexeme form are a
special case and they go together.  If you turn one off, then they are both
off.  But the display still uses either one.  I'm not sure if we should do
the same for gloss/definition however.  Probably not.

Ron, any thoughts?

**Comment by rmlockwood** [comment]
I like option 1 below. The reason I turned off Citation form, is that I wanted less information showing to the user so as not to be confusing. I think it makes sense that what they see on the left is the same thing they see for “word”. I’m not too worried that it shows different from the Manager. He/she should be able to deal with that.

 

It seems like gloss/definition is already working that way. I have definition turned off for contributor and glosses are showing in the side list.

 

Thanks,

Ron

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-18
