### ISSUE TITLE
Left side word list scrolls away for no reason

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#165]
1. Go to my Swedish project
2. Search for 'bakom' and click on it to go to the edit entry view
3. Go the bottom of the first meaning and add an example.

A couple seconds after the example is added, the left word list scrolls up so that 'bakom' is no longer in view. Very annoying!

The same thing seems to happen if you simply start typing data in the definition field. 

I'm using Chrome.

**Comment by rmunn** [comment]
Verified on my local installation. The trigger for this to happen is the auto-save kicking in. When the auto-save saves the entry, it tries to scroll the left side word list to make sure that the entry is in view. (This is so that when you create a new entry and fill it its lexeme form, it will be visible in the correct position in the list). But that is not working well with the "infinite scroll" feature of the left word list: the word list only loads a certain number of words at once (I think it's 50), and if the word it's trying to scroll to is too far down the list, it doesn't load enough words to reach the right point.

So if the word you're editing is lower than the top 50, this bug will cause it to move out of view. The solution to the bug is going to be to tweak the "scroll the current word into view" feature so that it knows how to load the correct "chunk" of 50 words in the list view.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-16
