### ISSUE TITLE
Gloss showing for a different analysis WS

### ISSUE THREAD

**Issue by rmdiamondl** [sillsdev/web-languageforge#17]
I was surprised to see a gloss line for Swedish in my Farsi project. That wasn't part of my FLEx project. I had previously imported my Swedish project. Maybe it picked it up from there.

**Comment by megahirt** [comment]
I believe this is a remnant from an old data set that did not clear out on the second import.  Right now we don't have a "clear the dictionary" button because of how dangerous that is, but I have had requests for it before so maybe we should have that functionality while we are in the testing phase.  I think the best thing would be to start a new dictionary project to make sure there is not left over data in there from a previous import.

**Comment by rmdiamondl** [comment]
I didn’t do multiple imports. I created a new project and imported once and this was the problem.

 

Ron
