### ISSUE TITLE
User admin page only lists a fraction of the users

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/web-languageforge#1770]
Tried to find a user today and noticed that the user admin page says there's only 290 users in Language Forge. That's not correct, there's a lot more. It also means we can't search for those other users.

**Comment by megahirt** [comment]
I thought I fixed this, but apparently not.  This was most likely introduced with #1706 and has to do with the [UserListModel checking for isDeleted being false](https://github.com/sillsdev/web-languageforge/blob/b2123ad2ca45a67bbd68381152e98b6f2bb5334a/src/Api/Model/Shared/UserListModel.php#L13) in Mongo.  The trouble is many user models were not migrated to include isDeleted set to false and so the query fails.  The solution is to run a database migration and if isDelete is unset on a UserModel, then set it to false.

**Comment by hahn-kev** [comment]
@rmunn would you take a look at this? Either do a migration as Chris mentioned, or modify the filter to include users where `isDeleted` is unset, but it's not clear if other features would still work with it unset so I'm not sure if that's the best plan. That set a big data migration like that is probably not ideal.

**Comment by rmunn** [comment]
The MongoDB migration is quite simple:

```js
use('scriptureforge')
db.users.update({isDeleted: null}, {'$set': {isDeleted: false}})
```

This works because [MongoDB treats a `field: null` condition as "field is null *or* not defined](https://www.mongodb.com/docs/manual/tutorial/query-for-null-fields/#equality-filter). We don't expect any fields to have `isDeleted: null` because of how our LF code strips nulls (and empty lists) out to reduce the size of MongoDB records. But in case one has slipped in there, this is the command to run.

**Comment by rmunn** [comment]
But I think I found the way to edit the query and not have to run a DB migration. PR incoming.
