### ISSUE TITLE
Viewing project page throws a 500

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/web-languageforge#1773]
open this page and there's a 500 error
https://languageforge.org/projects/smk-flex

**Comment by rmunn** [comment]
This may be related to an [undici bug](https://github.com/nodejs/undici/issues/583) that was closed a couple of years ago, but reports indicate it's still happening as recently as June 6, 2023. The Svelte-Kit console log shows "SocketError: other side closed", which is the subject line of that issue, and its discussion involves timeouts and HTTP keep-alive headers, which would make sense of why only large projects show this behavior. Further evidence: the Apache logs show:

```
"POST /api/sf HTTP/1.1" 500 211 "-" "undici"
```

So I'm inclined to try upgrading Svelte-Kit in next-app, which will pull in an undici upgrade, as the first step towards fixing this.

**Comment by rmunn** [comment]
Update: I copied the repository with rsync and then ran an hg clone that was purely *local*, no network involved so the only time involved in the clone was reconstructing the files from Mercurial history. It took 19 minutes and 15 seconds, adding 6567 changesets with 56114 changes to 279 files. That's... a lot. So I've created a project called `test-rmunn-smk-short` with Mercurial history truncated down to a single commit. I'm cloning that now into the live LF server and will test to see how the dashboard page behaves with the same number of dictionary entries but no Mercurial history.

**Comment by rmunn** [comment]
Answer appears to be that the shortened-history project still throws the 500 Internal Server Error on the dashboard page. Which means I'll be able to use the shortened-history project to repro the issue locally.

**Comment by rmunn** [comment]
I was able to get the shortened-history project to clone locally, and I saw something I hadn't been able to see when I tested this on the live server. On my dev machine, the PHP stack trace is visible, and the error is:

> Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/Api/Model/Shared/Mapper/MongoMapper.php on line 122

That's happening when it calls `MongoMapper->readListAsModels` in the `LexDbeDto::encode` call on Sf.php line 521:

https://github.com/sillsdev/web-languageforge/blob/11f21e7c1006764adfec8ec0ab006aaea872753a/src/Api/Service/Sf.php#L521

So it's unrelated to the undici bug after all. It's because next-app is calling `lex_stats`, which returns *all* the entries. What next-app is actually trying to do is get a count of how many entries are in the project, and how many have audio or a picture:

https://github.com/sillsdev/web-languageforge/blob/11f21e7c1006764adfec8ec0ab006aaea872753a/next-app/src/routes/projects/[project_code]/meta/+server.ts#L31-L43

But the PHP DTO code is coded to just return the whole list of entries.

Solving this is going to involve rewriting the PHP `lex_stats` handler to do the counting (including the "how many pictures?" and "how many audio?") on the server, and just sending a count to the frontend instead of sending the whole entire entry list.

**Comment by megahirt** [comment]
The decision to get all entries for the purposes of counting client side was not a good or performant one.  It was the cheapest way forward and now it looks like we need to re-write both the client and server side to adjust since we didn't really test with large enough datasets it seems.
