### ISSUE TITLE
Empty WS for Citation Form

### ISSUE THREAD

**Issue by rmdiamondl** [sillsdev/web-languageforge#19]
in my Farsi project, for some reason when I look at the configuration for Citation Form. There is a blank writing system. See image below:

![image](https://cloud.githubusercontent.com/assets/7088137/7515467/80853ea0-f4c7-11e4-877c-0d0d34d45e09.png)

**Comment by megahirt** [comment]
Ron,

Thank you for reporting this. Can you try to re-import the data into a new separate project and see if the problem is fixed? I have a hunch that the data was imported using older (buggy) code that is now fixed. If after importing into a new project you see the same empty writing system, please reply to this issue and we will look into it and fix it.

Thanks.

**Comment by rmdiamondl** [comment]
Same issue after a re-import.
