### ISSUE TITLE
Can't find lexeme when searching

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#34]
in my Persian project, if I search for the English word 'book', of the 15 words that match, none of them is 'کتاب'. I expected this word to show up since it matches wholly the search term. I kind find the word without a problem if I search for 'کَتاب'.

**Comment by megahirt** [comment]
Hi Ron,

Thanks for reporting this.  Can you send me a link to your languageforge.org project?  We'll investigate.

Thanks,

Chris

**Comment by rmlockwood** [comment]
https://languageforge.org/app/lexicon/573f3370863f1c8877d5c2f8/#/dbe

 

Thanks for looking into it!

 

Ron

**Comment by darcywong00** [comment]
Hi Ron

Just letting you know we're looking into this issue.  Our searchbox currently has a limitation where only the top 10 of _n_ results is visible.  When you search for `book`, you get 15 results, but the 15th hit `کَتاب` is hidden.  If you search for `book.pl`, you'll get `کَتاب` for the lone result.

We'll look into our options of making the search results more clearer, maybe a caption along lines of **"10 of 15 results"**

**Comment by darcywong00** [comment]
Depending on the how many search matches there are, I'll change the caption to one of the following:
```
1 match
6 matches
10 of 15 matches
```

This fix will be visible on languageforge.org when the send/receive functionality is released.

**Comment by megahirt** [comment]
I'll add a few comments:

- A very-short-term solution is to increase the number of visible results
to however many can be displayed on a reasonable sized computer screen.
I'm guessing we could change it to 15 without a problem, possibly even 20.

- Because the paging mechanism to scroll through the list view is tedious
(and possibly broken at the moment), searching is the only viable way to
browse to the entry.  So, if Ron cannot reach the entry by searching
(because of a limited result set size), we need to fix this as soon as we
can.

- A long term solution is to develop a flexible, resizable list view with a
filter control (which includes text search filter).  Instead of showing a
result set overlay, the list itself could reflect the current filter.  We
should develop this list view and filter control to be flexible for all
display sizes and can be used in the full blown list view and the mini list
view side bar in the entry view.

I'd like to re-open this issue and close it when Ron can get to his entry
in question.  Let's consider this closed when:
- Ron can search for the entry in question and access it
- The scroll mechanism to scroll through the entire list is functional.

Chris

**Comment by megahirt** [comment]
Re-open per my previous comments

**Comment by darcywong00** [comment]
Updated search box will return the top 50 matches, where 7 are displayed at a time, and now has a scrollbar so the user can get to those matches.
I also brought exact matches for the lexeme and sense to the top of the list.  In this specific use-case, the words with the meaning "book" are at the top of the list, but you'll still have to scroll to get to "book.pl".
