### ISSUE TITLE
S/R: Adding a new writing system in FLEx should add that writing system to LF and enable for all appropriate fields

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#35]
Rewording this issue since @rmunn recently fixed the original one.

**Comment by rmunn** [comment]
The current Send/Receive code only touches writing systems in LF during project creation. It's quite possible that we should do more (including, but not limited to, adding new writing systems in LF if they are added in FLEx), but this is more along the scope of a feature request since it will involve making major changes to how the Send/Receive process handles writing systems. So I'm tagging it as "enhancement", since the scope is larger than a simple bugfix.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-37
