### ISSUE TITLE
S/R: edits to some custom fields not preserved after Send/Receive

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#38]
Some edits in custom line fields are not being preserved after Send/Receive.

-Editing custom single line all or custom single line ref, saving, then Send/Receive --> the field is refreshed  with the original unchanged content
-Clearing a custom single line, then Send/Receive --> the original custom single line returns.

**Comment by rmunn** [comment]
I assume that "custom single line ref" in the description should be "custom single list ref". I tested this today and found that this is still in need of fixing on the Send/Receive side:

- Custom single list refs were originally designed to rely on GUID keys coming from LF, but LF has not yet been updated to use GUIDs as keys in option lists. Until that happens on the LF side, the custom single list ref S/R code needs to track the string key coming from LF and find that in the possibility list on the FW side. The ListConverter class should be used for this, since that's exactly what it's for.
- "Custom single line all" fields are fields of type MultiUnicode in FW. There is a bug in the S/R code where custom MultiUnicode fields are handled in the "read from FW" direction, but skipped in the "write to FW" direction.
- Clearing a custom single line may be hitting the code path where we say "if the input value is null, make no changes to FW". A custom single line field normally has a BSON representation like `{ fieldName: { en: { value: "contents" } } }`. But if the value is empty, that might be getting stripped by the Javascript which is configured to remove all fields that have empty values (so that the on-disk representation is smaller). We need to check for that case and handle it.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-36
