### ISSUE TITLE
S/R not working

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#42]
It doesn't appear that the syncing on the LF side is working at all for me. I've tried it several times. Here's the latest error.

![image](https://cloud.githubusercontent.com/assets/7088137/18028726/a7e530e0-6c3a-11e6-9bca-f5f311813711.png)

**Comment by megahirt** [comment]
When, a project is put on hold because of a crash in the send/receive
system, at this point the only way to get it unstuck is by the developers
helping out.  Soon you'll have the ability to delete the LF project and
start over with a fresh clone but that feature isn't quite ready yet .  On
Monday we'll investigate the specific cause of this crash.

**Comment by irahopkinson** [comment]
This issue has been resolved
