### ISSUE TITLE
Field-specific Input Systems not respected in editor entry view

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#995]
In the process of working on the `pce-flex` project, I have come across a situation where the "fields-specific input systems" settings are not being respected in the editor view.

1) Here are the input systems which are enabled for the project:
![image](https://user-images.githubusercontent.com/3444521/124871106-d6dd4280-dfed-11eb-9faa-1d620f704582.png)

2) Now, for the field "Word" (called "lexeme" under the hood), the overridden input systems are:
![image](https://user-images.githubusercontent.com/3444521/124871246-012f0000-dfee-11eb-99fb-bbd5fff5b95c.png)

3) The above settings do "stick" when you click apply to save the configuration.  However, the view of the entry remains the same, showing all 6 input systems, like this:
![image](https://user-images.githubusercontent.com/3444521/124871376-2c195400-dfee-11eb-81e2-2332fde51e34.png)

What is desired is for the entry view to only show the three input systems selected in the config, as in 3 above.

I note in the data for this project that the "overrideInputSystems" is true, and that the input systems listed are all 6, which explains why the editor is showing all six.
![image](https://user-images.githubusercontent.com/3444521/124871595-6aaf0e80-dfee-11eb-94f6-26b49fab6b81.png)

So the bug seems to be that the overridden input systems are not set correct in the right place in the config, where the editor view is expecting them.

Additionally, it seems odd that there is no way to "reset" or turn off the override.  This could cause problems.  What is the current meaning of "overrideInputSystems" if it is always true?

Ideally I would be able to debug [line 168 of lexicon-config.service.ts](https://github.com/sillsdev/web-languageforge/blob/master/src/angular-app/languageforge/lexicon/core/lexicon-config.service.ts#L168) to be able to see this occur on this project.  At this point I'm not actually sure how to do that.
![image](https://user-images.githubusercontent.com/3444521/124872546-97aff100-dfef-11eb-8293-ef3ec255a2a5.png)

**Comment by rmunn** [comment]
Looks like I broke this in https://github.com/sillsdev/web-languageforge/pull/711. I was trying to fix a bug without changing the model, but I used `overrideInputSystems` incorrectly. I thought it meant that the field configuration should override the input systems selected for the user, but it actually meant that the user's input systems would override the field configuration.

I'm working on a fix now, and the fix will actually make the model change that #711 should have included. The role views (which includes user views) will now gain a field called `inputSystems`, which will be an array of strings (each string will be an input system tag). Any role where that field is absent will be considered to have no overrides to input systems. That will be the case for most situations, and that also has the nice effect of letting us make this change without needing a migration script, because having that property absent will be what most projects want anyway. If the field is present, that is considered to be the only input systems that that role should see, and that list is **AND**ed with the input systems of a field to produce the overrides for that role in that field.

E.g., if a project has English, French and Thai writing systems, and `lexeme` is set to `['fr', 'th']` while one user's input system list is set to `['en', 'fr']`, then everyone else will see French and Thai in the lexeme field, but that user will only see French.

**Comment by megahirt** [comment]
Yes, this sounds correct to me.  Thank you for your work on this!  We need
it for the PCE project :)

**Comment by rmunn** [comment]
Should be fixed by PR #997.

**Comment by rmunn** [comment]
PR #997 fixes this, and has been merged now, so we can safely close this.
